version: '3.8'

services:
  # MongoDB database service
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: doc2formjson-mongodb-ssl
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=doc2formjson
      - MONGODB_APP_USERNAME=doc2formapp
      - MONGODB_APP_PASSWORD=apppassword123
    volumes:
      - mongodb_data_ssl:/data/db
      - mongodb_logs_ssl:/data/logs
      - ./mongodb/mongod.conf:/etc/mongod.conf:ro
      - ./mongodb/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - doc2formjson-ssl-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  # Ollama GPU service for LLM inference (Resource-Limited)
  ollama-gpu:
    build:
      context: ./ollama
      dockerfile: Dockerfile.minimal
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
      - OLLAMA_MODELS=qwen2.5vl:latest
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_GPU_MEMORY_FRACTION=0.3
      - OLLAMA_KEEP_ALIVE=2m
      - OLLAMA_MAX_QUEUE=1
    volumes:
      - ollama_models_ssl:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/ollama_ready" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - doc2formjson-ssl-network

  # Node.js API service for image description using Ollama
  doc2formjson-api:
    build:
      context: ./describeImge
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OLLAMA_BASE_URL=http://ollama-gpu:11434
      - DEFAULT_QWEN_MODEL_NAME=qwen2.5vl:latest
      - MONGODB_URI=mongodb://doc2formapp:apppassword123@mongodb:27017/doc2formjson
    restart: unless-stopped
    depends_on:
      - ollama-gpu
      - mongodb
    healthcheck:
      test: [ "CMD", "node", "-e", "const http = require('http'); const options = { port: process.env.PORT || 3000, timeout: 2000 }; const request = http.request(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); request.on('error', () => process.exit(1)); request.end();" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # Python Flask service for PDF to PNG conversion
  pdf-converter:
    build:
      context: ./pdf-png
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PORT=5001
    restart: unless-stopped
    volumes:
      - ./pdf-png/generated_pngs:/app/generated_pngs
      - generated_images_ssl:/app/generated_pngs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/", "||", "exit", "1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # Certbot for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: dynaform-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    networks:
      - doc2formjson-ssl-network
    # Run certbot in manual mode - certificates need to be obtained manually first
    # docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Nginx reverse proxy with SSL support
  dynaform-nginx:
    build:
      context: ./dynaform
      dockerfile: Dockerfile.ssl
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: dynaform-nginx-ssl
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP (redirects to HTTPS)
      - "443:443"   # HTTPS
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - SSL_EMAIL=${SSL_EMAIL:-admin@localhost}
    volumes:
      - ./dynaform/nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - ./pdf-png/generated_pngs:/usr/share/nginx/html/generated_pngs:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs_ssl:/var/log/nginx
    depends_on:
      - doc2formjson-api
      - pdf-converter
      - certbot
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

networks:
  doc2formjson-ssl-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  generated_images_ssl:
    driver: local
  ollama_models_ssl:
    driver: local
  mongodb_data_ssl:
    driver: local
  mongodb_logs_ssl:
    driver: local
  certbot_certs:
    driver: local
  certbot_www:
    driver: local
  certbot_logs:
    driver: local
  nginx_cache:
    driver: local
  nginx_logs_ssl:
    driver: local
