services:
  # MongoDB database service
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: doc2formjson-mongodb-ssl
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Remove authentication for simplified setup
      - MONGO_INITDB_DATABASE=doc2formjson
    volumes:
      - mongodb_data_ssl:/data/db
      - mongodb_logs_ssl:/data/logs
      - ./mongodb/mongod.noauth.conf:/etc/mongod.conf:ro
      - ./mongodb/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - doc2formjson-ssl-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  # Ollama GPU service for LLM inference (Resource-Limited)
  ollama-gpu:
    build:
      context: ./ollama
      dockerfile: Dockerfile.minimal
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
      - OLLAMA_MODELS=qwen2.5vl:latest
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_GPU_MEMORY_FRACTION=0.3
      - OLLAMA_KEEP_ALIVE=2m
      - OLLAMA_MAX_QUEUE=1
    volumes:
      - ollama_models_ssl:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/ollama_ready" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - doc2formjson-ssl-network

  # Node.js API service for image description using Ollama
  doc2formjson-api:
    build:
      context: ./server
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    # Note: Don't expose port 3000 externally - all traffic should go through nginx
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OLLAMA_BASE_URL=http://ai-agent:11435 ## this is the Ollama proxy port for real-time interception
      - DEFAULT_QWEN_MODEL_NAME=qwen2.5vl:latest
      - MONGODB_URI=mongodb://mongodb:27017/doc2formjson
      # Redis Configuration (matching server/.env)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      # WebAuthn/Passkey Configuration
      - RP_ID=dynaform.xyz
      - RP_NAME=DynaForm
      - WEBAUTHN_ORIGIN=https://dynaform.xyz
      # CORS Configuration  
      - CORS_ORIGIN=https://dynaform.xyz,http://dynaform.xyz
      - CORS_CREDENTIALS=true
    restart: unless-stopped
    depends_on:
      - ollama-gpu
      - mongodb
      - redis
    healthcheck:
      test: [ "CMD", "node", "-e", "const http = require('http'); const options = { port: process.env.PORT || 3000, timeout: 2000 }; const request = http.request(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); request.on('error', () => process.exit(1)); request.end();" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # AI Agent service for form processing and publishing
  ai-agent:
    build:
      context: ./ai-agent
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: dynaform-ai-agent-ssl
    restart: unless-stopped
    ports:
      - "8001:8001"    # FastAPI server port
      - "11435:11435"  # Ollama proxy port for real-time interception
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
      # MongoDB Configuration
      - MONGODB_URI=mongodb://mongodb:27017/doc2formjson
      - MONGODB_DATABASE=doc2formjson
      - FORMS_COLLECTION=generated_form
      # Ollama Configuration
      - OLLAMA_HOST=http://ollama-gpu:11434
      - OLLAMA_MODEL=qwen2.5vl:latest
      - OLLAMA_KEEP_ALIVE=20m
      - OLLAMA_TIMEOUT=10000
      # API Endpoints
      - VERIFIABLE_CONTRACT_API=http://verifiable-contract:3002/api/urls
      - FRONTEND_BASE_URL=https://dynaform.xyz
    # Default mode: interceptor (real-time conversation interception)
    # Override with: docker-compose run ai-agent server
    command: ["interceptor"]
    depends_on:
      - doc2formjson-api
      - verifiable-contract
      - mongodb
      - ollama-gpu
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]  # Simple Python availability check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # AI Agent in API server mode (alternative to interceptor mode)
  ai-agent-server:
    build:
      context: ./ai-agent
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: dynaform-ai-agent-server-ssl
    restart: unless-stopped
    ports:
      - "8002:8001"    # Use different external port to avoid conflicts
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
      # MongoDB Configuration
      - MONGODB_URI=mongodb://mongodb:27017/doc2formjson
      - MONGODB_DATABASE=doc2formjson
      - FORMS_COLLECTION=generated_form
      # Ollama Configuration
      - OLLAMA_HOST=http://ollama-gpu:11434
      - OLLAMA_MODEL=qwen2.5vl:latest
      - OLLAMA_KEEP_ALIVE=20m
      - OLLAMA_TIMEOUT=10000
      # API Endpoints
      - VERIFIABLE_CONTRACT_API=http://verifiable-contract:3002/api/urls
      - FRONTEND_BASE_URL=https://localhost
    # Run in server mode
    command: ["server"]
    depends_on:
      - doc2formjson-api
      - verifiable-contract
      - mongodb
      - ollama-gpu
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network
    profiles:
      - server  # Only start this service when explicitly requested

  # Verifiable URL Contract service for blockchain integration
  verifiable-contract:
    build:
      context: ./verifiable-url-contract
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: dynaform-verifiable-contract-ssl
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      # Blockchain Configuration (from verifiable-url-contract/.env)
      - PRIVATE_KEY=${BLOCKCHAIN_PRIVATE_KEY:-0x0386d60f46138cc1b2ec00b047dce71815fb28eb64b85f8ed7109fb5e17ebe84}
      - CONTRACT_ADDRESS=${BLOCKCHAIN_CONTRACT_ADDRESS:-0xC9C3Ef2Dc05f4f142F0180ae95E1606698311576}
      - PROVIDER_URL=${BLOCKCHAIN_PROVIDER_URL:-https://eth-sepolia.g.alchemy.com/v2/E4mBYdLyTQiGitVF-HhKH}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # Python Flask service for PDF to PNG conversion
  pdf-converter:
    build:
      context: ./pdf-png
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    pull_policy: build
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PORT=5001
    restart: unless-stopped
    volumes:
      - ./pdf-png/generated_pngs:/app/generated_pngs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

  # Redis service for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: dynaform-redis-ssl
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ""
    volumes:
      - redis_data_ssl:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - doc2formjson-ssl-network

  # Certbot for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: dynaform-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - certbot_logs:/var/log/letsencrypt
    networks:
      - doc2formjson-ssl-network
    # Run certbot in manual mode - certificates need to be obtained manually first
    # docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Nginx reverse proxy with SSL support (serves Angular frontend)
  dynaform-nginx:
    build:
      context: ./dynaform
      dockerfile: Dockerfile.ssl
      no_cache: true
      args:
        - BUILDKIT_INLINE_CACHE=0
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-default}
    container_name: dynaform-nginx-ssl
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP (redirects to HTTPS)
      - "443:443"   # HTTPS
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - SSL_EMAIL=${SSL_EMAIL:-admin@localhost}
    volumes:
      - ./dynaform/nginx.temp.conf:/etc/nginx/nginx.conf:ro
      - ./pdf-png/generated_pngs:/usr/share/nginx/html/generated_pngs:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs_ssl:/var/log/nginx
    depends_on:
      - doc2formjson-api
      - pdf-converter
      - ai-agent
      - verifiable-contract
      - redis
      - certbot
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - doc2formjson-ssl-network

networks:
  doc2formjson-ssl-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  generated_images_ssl:
    driver: local
  redis_data_ssl:
    driver: local
  mongodb_data_ssl:
    driver: local
  mongodb_logs_ssl:
    driver: local
  ollama_models_ssl:
    driver: local
  certbot_certs:
    driver: local
  certbot_www:
    driver: local
  certbot_logs:
    driver: local
  nginx_cache:
    driver: local
  nginx_logs_ssl:
    driver: local
